sudo: false
language: go
go:
  - 1.8.x
  - 1.9.x
  - master
install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go tool vet .
  - go test -v -race ./...
